-- MySQL Script generated by MySQL Workbench
-- Mon Jan 14 18:05:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema open_payments
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `open_payments` ;

-- -----------------------------------------------------
-- Schema open_payments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `open_payments` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema indicators
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `indicators` ;

-- -----------------------------------------------------
-- Schema indicators
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indicators` ;
USE `open_payments` ;

-- -----------------------------------------------------
-- Table `open_payments`.`d_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`d_hospital` (
  `teaching_hospital_id` BIGINT NOT NULL,
  `teaching_hospital_ccn` VARCHAR(6) NULL,
  `teaching_hospital_name` VARCHAR(100) NULL,
  PRIMARY KEY (`teaching_hospital_id`),
  UNIQUE INDEX `teaching_hospital_id_UNIQUE` (`teaching_hospital_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`d_investigator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`d_investigator` (
  `investigator_profile_id` BIGINT NOT NULL,
  `investigator_first_name` VARCHAR(20) NULL,
  `investigator_middle_name` VARCHAR(20) NULL,
  `investigator_last_name` VARCHAR(35) NULL,
  `investigator_name_suffix` VARCHAR(5) NULL,
  `investigator_primary_type` VARCHAR(50) NULL,
  `investigator_specialty` VARCHAR(300) NULL,
  `investigator_business_street_address_line1` VARCHAR(55) NULL,
  `investigator_business_street_address_line2` VARCHAR(55) NULL,
  `investigator_city` VARCHAR(40) NULL,
  `investigator_postal_code` VARCHAR(20) NULL,
  `investigator_zip_code` VARCHAR(10) NULL,
  `investigator_province` VARCHAR(20) NULL,
  `investigator_state` CHAR(2) NULL,
  `investigator_country` VARCHAR(100) NULL,
  `investigator_license_state_code1` CHAR(2) NULL,
  `investigator_license_state_code2` CHAR(2) NULL,
  `investigator_license_state_code3` CHAR(2) NULL,
  `investigator_license_state_code4` CHAR(2) NULL,
  `investigator_license_state_code5` CHAR(2) NULL,
  PRIMARY KEY (`investigator_profile_id`),
  UNIQUE INDEX `investigator_profile_id_UNIQUE` (`investigator_profile_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`d_payer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`d_payer` (
  `applicable_payer_id` BIGINT NOT NULL,
  `applicable_payer_name` VARCHAR(100) NULL,
  `applicable_payer_state` CHAR(2) NULL,
  `applicable_payer_country` VARCHAR(100) NULL,
  `submitting_payer_name` VARCHAR(100) NULL,
  PRIMARY KEY (`applicable_payer_id`),
  UNIQUE INDEX `applicable_payer_id_UNIQUE` (`applicable_payer_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`d_physician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`d_physician` (
  `physician_profile_id` BIGINT NOT NULL,
  `physician_first_name` VARCHAR(20) NULL,
  `physician_middle_name` VARCHAR(20) NULL,
  `physician_last_name` VARCHAR(35) NULL,
  `physician_name_suffix` VARCHAR(5) NULL,
  `physician_primary_type` VARCHAR(100) NULL,
  `physician_specialty` VARCHAR(300) NULL,
  `physician_license_state_code1` CHAR(2) NULL,
  `physician_license_state_code2` CHAR(2) NULL,
  `physician_license_state_code3` CHAR(2) NULL,
  `physician_license_state_code4` CHAR(2) NULL,
  `physician_license_state_code5` CHAR(2) NULL,
  PRIMARY KEY (`physician_profile_id`),
  UNIQUE INDEX `physician_profile_id_UNIQUE` (`physician_profile_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`d_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`d_product` (
  `product_name` VARCHAR(100) NOT NULL,
  `covered_or_noncovered_indicator` VARCHAR(100) NULL,
  `product_type` VARCHAR(100) NULL,
  `product_category_or_therapeutic_area` VARCHAR(100) NULL,
  `associated_drug_or_biological_ndc` VARCHAR(100) NULL,
  UNIQUE INDEX `name_product_UNIQUE` (`product_name` ASC) VISIBLE,
  PRIMARY KEY (`product_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment` (
  `record_id` BIGINT NOT NULL,
  `date_of_payment` DATE NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `noncovered_recipient_entity_name` VARCHAR(50) NULL,
  `number_of_payments_included` INT NULL,
  `program_year` INT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  `delay_in_publication_indicator` CHAR(3) NULL,
  `dispute_status_for_publication` CHAR(3) NULL,
  `payment_publication_date` DATE NULL,
  `covered_recipient_type` VARCHAR(50) NULL,
  `recipient_primary_business_street_address_line1` VARCHAR(55) NULL,
  `recipient_primary_business_street_address_line2` VARCHAR(55) NULL,
  `recipient_city` VARCHAR(40) NULL,
  `recipient_postal_code` VARCHAR(20) NULL,
  `recipient_zip_code` VARCHAR(10) NULL,
  `recipient_province` VARCHAR(20) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `related_product_indicator` CHAR(3) NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `state_of_travel` CHAR(2) NULL,
  `preclinical_research_indicator` CHAR(3) NULL,
  `clinicaltrials_gov_identifier` VARCHAR(11) NULL,
  `context_of_research` VARCHAR(500) NULL,
  `expenditure_category1` VARCHAR(50) NULL,
  `expenditure_category2` VARCHAR(50) NULL,
  `expenditure_category3` VARCHAR(50) NULL,
  `expenditure_category4` VARCHAR(50) NULL,
  `expenditure_category5` VARCHAR(50) NULL,
  `expenditure_category6` VARCHAR(50) NULL,
  `name_of_study` VARCHAR(500) NULL,
  `research_information_link` VARCHAR(2083) NULL,
  `interest_held_by_physician` VARCHAR(50) NULL,
  `physician_ownership_indicator` CHAR(3) NULL,
  `terms_of_interest` VARCHAR(500) NULL,
  `total_amount_invested_usdollars` FLOAT NULL,
  `value_of_interest` FLOAT NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `contextual_information` VARCHAR(500) NULL,
  `d_physician_physician_profile_id` BIGINT NOT NULL,
  `d_payer_applicable_payer_id` BIGINT NOT NULL,
  `d_hospital_teaching_hospital_id` BIGINT NOT NULL,
  `d_investigator_investigator_profile_id` BIGINT NOT NULL,
  PRIMARY KEY (`record_id`, `d_physician_physician_profile_id`, `d_payer_applicable_payer_id`, `d_hospital_teaching_hospital_id`, `d_investigator_investigator_profile_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_payment_d_physician1_idx` (`d_physician_physician_profile_id` ASC) VISIBLE,
  INDEX `fk_h_payment_d_payer1_idx` (`d_payer_applicable_payer_id` ASC) VISIBLE,
  INDEX `fk_h_payment_d_hospital1_idx` (`d_hospital_teaching_hospital_id` ASC) VISIBLE,
  INDEX `fk_h_payment_d_investigator1_idx` (`d_investigator_investigator_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_payment_d_physician1`
    FOREIGN KEY (`d_physician_physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_payment_d_payer1`
    FOREIGN KEY (`d_payer_applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_payment_d_hospital1`
    FOREIGN KEY (`d_hospital_teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_payment_d_investigator1`
    FOREIGN KEY (`d_investigator_investigator_profile_id`)
    REFERENCES `open_payments`.`d_investigator` (`investigator_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_details_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_details_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `year_of_payment` INT NULL,
  `month_of_payment` INT NULL,
  `day_of_payment` INT NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `number_of_payments_included` INT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_p_d_2013_d_payer1_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_d_2013_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_details_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_details_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `year_of_payment` INT NULL,
  `month_of_payment` INT NULL,
  `day_of_payment` INT NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `number_of_payments_included` INT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_p_d_2014_d_payer1_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_d_2014_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_details_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_details_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `year_of_payment` INT NULL,
  `month_of_payment` INT NULL,
  `day_of_payment` INT NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `number_of_payments_included` INT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_p_d_2015_d_payer1_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_d_2015_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_details_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_details_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `year_of_payment` INT NULL,
  `month_of_payment` INT NULL,
  `day_of_payment` INT NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `number_of_payments_included` INT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_p_d_2016_d_payer1_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_d_2016_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_details_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_details_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `year_of_payment` INT NULL,
  `month_of_payment` INT NULL,
  `day_of_payment` INT NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `number_of_payments_included` INT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_p_d_2017_d_payer1_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_d_2017_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h_teaching_hospital_id_2013_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h_teaching_hospital_id_2013_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h_teaching_hospital_id_2014_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h_teaching_hospital_id_2014_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h_teaching_hospital_id_2015_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h_teaching_hospital_id_2015_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h_teaching_hospital_id_2016_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h_teaching_hospital_id_2016_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h_teaching_hospital_id_2017_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h_teaching_hospital_id_2017_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_3p_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_3p_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h3p_teaching_hospital_id_2013_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h3p_teaching_hospital_id_2013_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_3p_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_3p_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h3p_teaching_hospital_id_2014_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h3p_teaching_hospital_id_2014_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_3p_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_3p_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h3p_teaching_hospital_id_2015_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h3p_teaching_hospital_id_2015_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_3p_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_3p_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h3p_teaching_hospital_id_2016_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h3p_teaching_hospital_id_2016_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_hospital_3p_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_hospital_3p_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_h3p_teaching_hospital_id_2017_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_h3p_teaching_hospital_id_2017_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_investigator_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_investigator_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `physician_profile_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `investigator_profile_id` BIGINT NOT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  INDEX `h_p_i_teaching_hospital_id_2013_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  INDEX `h_p_i_physician_profile_id_2013_idx` (`physician_profile_id` ASC) INVISIBLE,
  INDEX `h_p_i_investigator_profile_id_2013_idx` (`investigator_profile_id` ASC) VISIBLE,
  INDEX `h_p_i_applicable_payer_id_2013_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `h_p_i_teaching_hospital_id_2013_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_physician_profile_id_2013_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_investigator_profile_id_2013_FK`
    FOREIGN KEY (`investigator_profile_id`)
    REFERENCES `open_payments`.`d_investigator` (`investigator_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_applicable_payer_id_2013_FK`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_investigator_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_investigator_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `physician_profile_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `investigator_profile_id` BIGINT NOT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  INDEX `h_p_i_teaching_hospital_id_2014_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  INDEX `h_p_i_physician_profile_id_2014_idx` (`physician_profile_id` ASC) INVISIBLE,
  INDEX `h_p_i_investigator_profile_id_2014_idx` (`investigator_profile_id` ASC) VISIBLE,
  INDEX `h_p_i_applicable_payer_id_2014_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `h_p_i_teaching_hospital_id_2014_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_physician_profile_id_2014_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_investigator_profile_id_2014_FK`
    FOREIGN KEY (`investigator_profile_id`)
    REFERENCES `open_payments`.`d_investigator` (`investigator_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_applicable_payer_id_2014_FK`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_investigator_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_investigator_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `physician_profile_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `investigator_profile_id` BIGINT NOT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  INDEX `h_p_i_teaching_hospital_id_2015_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  INDEX `h_p_i_physician_profile_id_2015_idx` (`physician_profile_id` ASC) INVISIBLE,
  INDEX `h_p_i_investigator_profile_id_2015_idx` (`investigator_profile_id` ASC) VISIBLE,
  INDEX `h_p_i_applicable_payer_id_2015_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `h_p_i_teaching_hospital_id_2015_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_physician_profile_id_2015_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_investigator_profile_id_2015_FK`
    FOREIGN KEY (`investigator_profile_id`)
    REFERENCES `open_payments`.`d_investigator` (`investigator_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_applicable_payer_id_2015_FK`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_investigator_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_investigator_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `physician_profile_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `investigator_profile_id` BIGINT NOT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  INDEX `h_p_i_teaching_hospital_id_2016_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  INDEX `h_p_i_physician_profile_id_2016_idx` (`physician_profile_id` ASC) INVISIBLE,
  INDEX `h_p_i_investigator_profile_id_2016_idx` (`investigator_profile_id` ASC) VISIBLE,
  INDEX `h_p_i_applicable_payer_id_2016_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `h_p_i_teaching_hospital_id_2016_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_physician_profile_id_2016_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_investigator_profile_id_2016_FK`
    FOREIGN KEY (`investigator_profile_id`)
    REFERENCES `open_payments`.`d_investigator` (`investigator_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_applicable_payer_id_2016_FK`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_investigator_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_investigator_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `physician_profile_id` BIGINT NULL,
  `teaching_hospital_id` BIGINT NULL,
  `investigator_profile_id` BIGINT NOT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  INDEX `h_p_i_teaching_hospital_id_2017_idx` (`teaching_hospital_id` ASC) INVISIBLE,
  INDEX `h_p_i_physician_profile_id_2017_idx` (`physician_profile_id` ASC) INVISIBLE,
  INDEX `h_p_i_investigator_profile_id_2017_idx` (`investigator_profile_id` ASC) VISIBLE,
  INDEX `h_p_i_applicable_payer_id_2017_idx` (`applicable_payer_id` ASC) VISIBLE,
  CONSTRAINT `h_p_i_teaching_hospital_id_2017_FK`
    FOREIGN KEY (`teaching_hospital_id`)
    REFERENCES `open_payments`.`d_hospital` (`teaching_hospital_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_physician_profile_id_2017_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_investigator_profile_id_2017_FK`
    FOREIGN KEY (`investigator_profile_id`)
    REFERENCES `open_payments`.`d_investigator` (`investigator_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_p_i_applicable_payer_id_2017_FK`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_list_physician_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_list_physician_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_l_p_2013_d_payer1_idx` (`applicable_payer_id` ASC) INVISIBLE,
  INDEX `fk_h_l_p_2013_d_physician1_idx` (`physician_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_l_p_2013_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_p_l_p_2013_d_physician1`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_list_physician_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_list_physician_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_l_p_2014_d_payer1_idx` (`applicable_payer_id` ASC) INVISIBLE,
  INDEX `fk_h_l_p_2014_d_physician1_idx` (`physician_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_l_p_2014_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_p_l_p_2014_d_physician1`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_list_physician_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_list_physician_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_l_p_2015_d_payer1_idx` (`applicable_payer_id` ASC) INVISIBLE,
  INDEX `fk_h_l_p_2015_d_physician1_idx` (`physician_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_l_p_2015_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_p_l_p_2015_d_physician1`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_list_physician_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_list_physician_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_l_p_2016_d_payer1_idx` (`applicable_payer_id` ASC) INVISIBLE,
  INDEX `fk_h_l_p_2016_d_physician1_idx` (`physician_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_l_p_2016_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_p_l_p_2016_d_physician1`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_list_physician_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_list_physician_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_l_p_2017_d_payer1_idx` (`applicable_payer_id` ASC) INVISIBLE,
  INDEX `fk_h_l_p_2017_d_physician1_idx` (`physician_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_p_l_p_2017_d_payer1`
    FOREIGN KEY (`applicable_payer_id`)
    REFERENCES `open_payments`.`d_payer` (`applicable_payer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_p_l_p_2017_d_physician1`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_noncovered_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_noncovered_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `noncovered_recipient_entity_name` VARCHAR(50) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_noncovered_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_noncovered_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `noncovered_recipient_entity_name` VARCHAR(50) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_noncovered_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_noncovered_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `noncovered_recipient_entity_name` VARCHAR(50) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_noncovered_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_noncovered_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `noncovered_recipient_entity_name` VARCHAR(50) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_noncovered_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_noncovered_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `noncovered_recipient_entity_name` VARCHAR(50) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `physician_ownership_indicator` CHAR(3) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p_physician_profile_id_2013_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p_physician_profile_id_2013_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `physician_ownership_indicator` CHAR(3) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p_physician_profile_id_2014_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p_physician_profile_id_2014_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `physician_ownership_indicator` CHAR(3) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p_physician_profile_id_2015_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p_physician_profile_id_2015_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `physician_ownership_indicator` CHAR(3) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p_physician_profile_id_2016_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p_physician_profile_id_2016_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `physician_ownership_indicator` CHAR(3) NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p_physician_profile_id_2017_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p_physician_profile_id_2017_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_3p_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_3p_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p3p_physician_profile_id_2013_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p3p_physician_profile_id_2013_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_3p_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_3p_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p3p_physician_profile_id_2014_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p3p_physician_profile_id_2014_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_3p_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_3p_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p3p_physician_profile_id_2015_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p3p_physician_profile_id_2015_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_3p_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_3p_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p3p_physician_profile_id_2016_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p3p_physician_profile_id_2016_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_physician_3p_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_physician_3p_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `charity_indicator` CHAR(3) NULL,
  `name_of_third_party_entity_receiving_payment` VARCHAR(50) NULL,
  `third_party_equals_covered_recipient_indicator` CHAR(3) NULL,
  `third_party_payment_recipient_indicator` VARCHAR(50) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_p3p_physician_profile_id_2017_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_p3p_physician_profile_id_2017_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_poi_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_poi_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `interest_held_by_physician` VARCHAR(50) NULL,
  `terms_of_interest` VARCHAR(500) NULL,
  `total_amount_invested_usdollars` FLOAT NULL,
  `value_of_interest` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_poi_physician_profile_id_2013_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_poi_physician_profile_id_2013_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_poi_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_poi_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `interest_held_by_physician` VARCHAR(50) NULL,
  `terms_of_interest` VARCHAR(500) NULL,
  `total_amount_invested_usdollars` FLOAT NULL,
  `value_of_interest` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_poi_physician_profile_id_2014_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_poi_physician_profile_id_2014_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_poi_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_poi_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `interest_held_by_physician` VARCHAR(50) NULL,
  `terms_of_interest` VARCHAR(500) NULL,
  `total_amount_invested_usdollars` FLOAT NULL,
  `value_of_interest` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_poi_physician_profile_id_2015_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_poi_physician_profile_id_2015_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_poi_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_poi_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `interest_held_by_physician` VARCHAR(50) NULL,
  `terms_of_interest` VARCHAR(500) NULL,
  `total_amount_invested_usdollars` FLOAT NULL,
  `value_of_interest` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_poi_physician_profile_id_2016_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_poi_physician_profile_id_2016_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_poi_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_poi_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `interest_held_by_physician` VARCHAR(50) NULL,
  `terms_of_interest` VARCHAR(500) NULL,
  `total_amount_invested_usdollars` FLOAT NULL,
  `value_of_interest` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `h_p_poi_physician_profile_id_2017_idx` (`physician_profile_id` ASC) INVISIBLE,
  CONSTRAINT `h_p_poi_physician_profile_id_2017_FK`
    FOREIGN KEY (`physician_profile_id`)
    REFERENCES `open_payments`.`d_physician` (`physician_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_product` (
  `record_id` BIGINT NOT NULL,
  `product_name` VARCHAR(100) NULL,
  `d_product_product_name` VARCHAR(100) NOT NULL,
  `h_payment_record_id` BIGINT NOT NULL,
  PRIMARY KEY (`record_id`, `d_product_product_name`, `h_payment_record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `fk_h_payment_product_d_product1_idx` (`d_product_product_name` ASC) VISIBLE,
  INDEX `fk_h_payment_product_h_payment1_idx` (`h_payment_record_id` ASC) VISIBLE,
  CONSTRAINT `fk_h_payment_product_d_product1`
    FOREIGN KEY (`d_product_product_name`)
    REFERENCES `open_payments`.`d_product` (`product_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_h_payment_product_h_payment1`
    FOREIGN KEY (`h_payment_record_id`)
    REFERENCES `open_payments`.`h_payment` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_recipient_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_recipient_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_recipient_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_recipient_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_recipient_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_recipient_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_recipient_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_recipient_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_recipient_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_recipient_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `recipient_state` CHAR(2) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_travel_2013`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_travel_2013` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `state_of_travel` CHAR(2) NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_travel_2014`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_travel_2014` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `state_of_travel` CHAR(2) NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_travel_2015`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_travel_2015` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `state_of_travel` CHAR(2) NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_travel_2016`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_travel_2016` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `state_of_travel` CHAR(2) NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_payments`.`h_payment_travel_2017`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `open_payments`.`h_payment_travel_2017` (
  `record_id` BIGINT NOT NULL,
  `applicable_payer_id` BIGINT NULL,
  `type_of_recipient` CHAR NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `state_of_travel` CHAR(2) NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `total_amount_of_payment_usdollars` FLOAT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `indicators` ;

-- -----------------------------------------------------
-- Table `indicators`.`interest_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicators`.`interest_analysis` (
  `year` VARCHAR(5) NULL,
  `physician_profile_id` BIGINT NULL,
  `recipient_country` VARCHAR(100) NULL,
  `recipient_state` CHAR(2) NULL,
  `interest` VARCHAR(3) NULL,
  `applicable_payer_id` BIGINT NULL,
  `sum_invested` DOUBLE NULL,
  `sum_payment` DOUBLE NULL,
  `p_i_ratio` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicators`.`location_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicators`.`location_analysis` (
  `year` VARCHAR(5) NULL,
  `type_of_recipient` CHAR NULL,
  `recipient_country` VARCHAR(100) NULL,
  `recipient_state` CHAR(2) NULL,
  `num` FLOAT NULL,
  `value_sum` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicators`.`ranking_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicators`.`ranking_analysis` (
  `year` VARCHAR(5) NULL,
  `type` CHAR NULL,
  `name` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `state` CHAR(2) NULL,
  `num` INT NULL,
  `value_sum` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicators`.`third_party_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicators`.`third_party_analysis` (
  `year` VARCHAR(5) NULL,
  `type` CHAR NULL,
  `tp_name` VARCHAR(100) NULL,
  `recipient_country` VARCHAR(100) NULL,
  `recipient_state` CHAR(2) NULL,
  `charity_indicator` CHAR(3) NULL,
  `num` INT NULL,
  `value_sum` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicators`.`travel_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicators`.`travel_analysis` (
  `year` VARCHAR(5) NULL,
  `type_of_recipient` CHAR NULL,
  `country_of_travel` VARCHAR(100) NULL,
  `state_of_travel` CHAR(2) NULL,
  `city_of_travel` VARCHAR(40) NULL,
  `num` FLOAT NULL,
  `value_sum` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicators`.`type_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicators`.`type_analysis` (
  `year` VARCHAR(5) NULL,
  `type_of_recipient` CHAR NULL,
  `form_of_payment` VARCHAR(100) NULL,
  `nature_of_payment` VARCHAR(200) NULL,
  `num` FLOAT NULL,
  `value_sum` DOUBLE NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
